/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./views/**/*.ejs', './public/**/*.js'],
  safelist: [
    // text part
    'text-red-bull', 'text-williams', 'text-racing-bulls', 'text-rb', 'text-racing-bulls', 'text-mclaren', 'text-alpine', 'text-ferrari', 'text-mercedes', 'text-aston-martin', 'text-haas', 'text-kick-sauber', 'text-sauber', 'text-stewardstxt', 'bg-stewardsbg', 'bg-red-bull', 'bg-williams', 'bg-racing-bulls', 'bg-rb', 'bg-mclaren', 'bg-alpine', 'bg-ferrari', 'bg-mercedes', 'bg-aston-martin', 'bg-haas', 'bg-kick-sauber', 'bg-sauber', 'border-red-bull', 'border-williams', 'border-racing-bulls', 'border-rb', 'border-mclaren', 'border-alpine', 'border-ferrari', 'border-mercedes', 'border-aston-martin', 'border-haas', 'border-kick-sauber', 'border-sauber', 'text-deconnect', 'text-gold', 'text-adams', 'text-afm', 'text-ags', 'text-alfa-romeo', 'text-alfa-special', 'text-alphatauri', 'text-alta', 'text-amon', 'text-andrea-moda', 'text-apollon', 'text-arrows', 'text-arzani-volpini', 'text-aston-butterworth', 'text-ats-wheels', 'text-ats', 'text-balsa', 'text-bar', 'text-behra-porsche', 'text-bellasi', 'text-benetton', 'text-bmw-sauber', 'text-bmw', 'text-boro', 'text-brabham', 'text-brawn', 'text-brm', 'text-bromme', 'text-brp', 'text-bugatti', 'text-caterham', 'text-christensen', 'text-cisitalia', 'text-coloni', 'text-connaught', 'text-connew', 'text-cooper', 'text-dallara', 'text-de-tomaso', 'text-deidt', 'text-del-roy', 'text-derrington-francis', 'text-dunn', 'text-eagle', 'text-eifelland', 'text-elder', 'text-emeryson', 'text-emw', 'text-enb', 'text-ensign', 'text-epperly', 'text-era', 'text-eurobrun', 'text-ewing', 'text-ferguson', 'text-first', 'text-fittipaldi', 'text-fondmetal', 'text-footwork', 'text-force-india', 'text-forti', 'text-frank-williams-racing-cars', 'text-frazer-nash', 'text-fry', 'text-gilby', 'text-gordini', 'text-greifzu', 'text-hall', 'text-heck', 'text-hesketh', 'text-hill', 'text-honda', 'text-hrt', 'text-hwm', 'text-iso-marlboro', 'text-jaguar', 'text-jbw', 'text-jordan', 'text-kauhsen', 'text-klenk', 'text-kojima', 'text-krakau', 'text-kurtis-kraft', 'text-kuzma', 'text-lancia', 'text-langley', 'text-larrousse', 'text-lds', 'text-lec', 'text-lesovsky', 'text-leyton-house', 'text-life', 'text-ligier', 'text-lola', 'text-lotus-f1', 'text-lotus-racing', 'text-lotus', 'text-lyncar', 'text-maki', 'text-manor', 'text-march', 'text-marchese', 'text-martini', 'text-marussia', 'text-maserati', 'text-matra', 'text-mcguire',
    'text-merzario', 'text-meskowski', 'text-midland', 'text-minardi', 'text-modena', 'text-moore', 'text-nacke', 'text-nichels', 'text-olson', 'text-onyx', 'text-osca', 'text-osella', 'text-pacific', 'text-pankratz', 'text-parnelli', 'text-pawl', 'text-penske', 'text-phillips', 'text-politoys', 'text-porsche', 'text-prost', 'text-protos', 'text-racing-point', 'text-rae', 'text-ram', 'text-rebaque', 'text-reif', 'text-renault', 'text-rial', 'text-scarab', 'text-schroeder', 'text-scirocco', 'text-shadow', 'text-shannon', 'text-sherman', 'text-simca-gordini', 'text-simtek', 'text-snowberger', 'text-spirit', 'text-spyker', 'text-stebro', 'text-stevens', 'text-stewart', 'text-super-aguri', 'text-surtees', 'text-sutton', 'text-talbot-lago', 'text-tec-mec', 'text-tecno', 'text-theodore', 'text-token', 'text-toleman', 'text-toro-rosso', 'text-toyota', 'text-trevis', 'text-trojan', 'text-turner', 'text-tyrrell', 'text-vanwall', 'text-venturi', 'text-veritas', 'text-virgin', 'text-watson', 'text-wetteroth', 'text-wolf-williams', 'text-wolf', 'text-zakspeed',

    // background part
    'bg-adams', 'bg-afm', 'bg-ags', 'bg-alfa-romeo', 'bg-alfa-special', 'bg-alphatauri', 'bg-alta', 'bg-amon', 'bg-andrea-moda', 'bg-apollon', 'bg-arrows', 'bg-arzani-volpini', 'bg-aston-butterworth', 'bg-ats-wheels', 'bg-ats', 'bg-balsa', 'bg-bar', 'bg-behra-porsche', 'bg-bellasi', 'bg-benetton', 'bg-bmw-sauber', 'bg-bmw', 'bg-boro', 'bg-brabham', 'bg-brawn', 'bg-brm', 'bg-bromme', 'bg-brp', 'bg-bugatti', 'bg-caterham', 'bg-christensen', 'bg-cisitalia', 'bg-coloni', 'bg-connaught', 'bg-connew', 'bg-cooper', 'bg-dallara', 'bg-de-tomaso', 'bg-deidt', 'bg-del-roy', 'bg-derrington-francis', 'bg-dunn', 'bg-eagle', 'bg-eifelland', 'bg-elder', 'bg-emeryson', 'bg-emw', 'bg-enb', 'bg-ensign', 'bg-epperly', 'bg-era', 'bg-eurobrun', 'bg-ewing', 'bg-ferguson', 'bg-first', 'bg-fittipaldi', 'bg-fondmetal', 'bg-footwork', 'bg-force-india', 'bg-forti', 'bg-frank-williams-racing-cars', 'bg-frazer-nash', 'bg-fry', 'bg-gilby', 'bg-gordini', 'bg-greifzu', 'bg-hall', 'bg-heck', 'bg-hesketh', 'bg-hill', 'bg-honda', 'bg-hrt', 'bg-hwm', 'bg-iso-marlboro', 'bg-jaguar', 'bg-jbw', 'bg-jordan', 'bg-kauhsen', 'bg-klenk', 'bg-kojima', 'bg-krakau', 'bg-kurtis-kraft', 'bg-kuzma', 'bg-lancia', 'bg-langley', 'bg-larrousse', 'bg-lds', 'bg-lec', 'bg-lesovsky', 'bg-leyton-house', 'bg-life', 'bg-ligier', 'bg-lola', 'bg-lotus-f1', 'bg-lotus-racing', 'bg-lotus', 'bg-lyncar', 'bg-maki', 'bg-manor', 'bg-march', 'bg-marchese', 'bg-martini', 'bg-marussia', 'bg-maserati', 'bg-matra', 'bg-mcguire', 'bg-merzario', 'bg-meskowski', 'bg-midland', 'bg-minardi', 'bg-modena', 'bg-moore', 'bg-nacke', 'bg-nichels', 'bg-olson', 'bg-onyx', 'bg-osca', 'bg-osella', 'bg-pacific', 'bg-pankratz', 'bg-parnelli', 'bg-pawl', 'bg-penske', 'bg-phillips', 'bg-politoys', 'bg-porsche', 'bg-prost', 'bg-protos', 'bg-racing-point', 'bg-rae', 'bg-ram', 'bg-rebaque', 'bg-reif', 'bg-renault', 'bg-rial', 'bg-scarab', 'bg-schroeder', 'bg-scirocco', 'bg-shadow', 'bg-shannon', 'bg-sherman', 'bg-simca-gordini', 'bg-simtek', 'bg-snowberger', 'bg-spirit', 'bg-spyker', 'bg-stebro', 'bg-stevens', 'bg-stewart', 'bg-super-aguri', 'bg-surtees', 'bg-sutton', 'bg-talbot-lago', 'bg-tec-mec', 'bg-tecno', 'bg-theodore', 'bg-token', 'bg-toleman', 'bg-toro-rosso', 'bg-toyota', 'bg-trevis', 'bg-trojan', 'bg-turner', 'bg-tyrrell', 'bg-vanwall', 'bg-venturi', 'bg-veritas', 'bg-virgin', 'bg-watson', 'bg-wetteroth', 'bg-wolf-williams', 'bg-wolf', 'bg-zakspeed',

    // border part
    'border-adams', 'border-afm', 'border-ags', 'border-alfa-romeo', 'border-alfa-special', 'border-alphatauri', 'border-alta', 'border-amon', 'border-andrea-moda', 'border-apollon', 'border-arrows', 'border-arzani-volpini', 'border-aston-butterworth', 'border-ats-wheels', 'border-ats', 'border-balsa', 'border-bar', 'border-behra-porsche', 'border-bellasi', 'border-benetton', 'border-bmw-sauber', 'border-bmw', 'border-boro', 'border-brabham', 'border-brawn', 'border-brm', 'border-bromme', 'border-brp', 'border-bugatti', 'border-caterham', 'border-christensen', 'border-cisitalia', 'border-coloni', 'border-connaught', 'border-connew', 'border-cooper', 'border-dallara', 'border-de-tomaso', 'border-deidt', 'border-del-roy', 'border-derrington-francis', 'border-dunn', 'border-eagle', 'border-eifelland', 'border-elder', 'border-emeryson', 'border-emw', 'border-enb', 'border-ensign', 'border-epperly', 'border-era', 'border-eurobrun', 'border-ewing', 'border-ferguson', 'border-first', 'border-fittipaldi', 'border-fondmetal', 'border-footwork', 'border-force-india', 'border-forti', 'border-frank-williams-racing-cars', 'border-frazer-nash', 'border-fry', 'border-gilby', 'border-gordini', 'border-greifzu', 'border-hall', 'border-heck', 'border-hesketh', 'border-hill', 'border-honda', 'border-hrt', 'border-hwm', 'border-iso-marlboro', 'border-jaguar', 'border-jbw', 'border-jordan', 'border-kauhsen', 'border-klenk', 'border-kojima', 'border-krakau', 'border-kurtis-kraft', 'border-kuzma', 'border-lancia', 'border-langley', 'border-larrousse', 'border-lds', 'border-lec', 'border-lesovsky', 'border-leyton-house', 'border-life', 'border-ligier', 'border-lola', 'border-lotus-f1', 'border-lotus-racing', 'border-lotus', 'border-lyncar', 'border-maki', 'border-manor', 'border-march', 'border-marchese', 'border-martini', 'border-marussia', 'border-maserati', 'border-matra', 'border-mcguire', 'border-merzario', 'border-meskowski', 'border-midland', 'border-minardi', 'border-modena', 'border-moore', 'border-nacke', 'border-nichels', 'border-olson', 'border-onyx', 'border-osca', 'border-osella', 'border-pacific', 'border-pankratz', 'border-parnelli', 'border-pawl', 'border-penske', 'border-phillips', 'border-politoys', 'border-porsche', 'border-prost', 'border-protos', 'border-racing-point', 'border-rae', 'border-ram', 'border-rebaque', 'border-reif', 'border-renault', 'border-rial',
    'border-scarab', 'border-schroeder', 'border-scirocco', 'border-shadow', 'border-shannon', 'border-sherman', 'border-simca-gordini', 'border-simtek', 'border-snowberger', 'border-spirit', 'border-spyker', 'border-stebro', 'border-stevens', 'border-stewart', 'border-super-aguri', 'border-surtees', 'border-sutton', 'border-talbot-lago', 'border-tec-mec', 'border-tecno', 'border-theodore', 'border-token', 'border-toleman', 'border-toro-rosso', 'border-toyota', 'border-trevis', 'border-trojan', 'border-turner', 'border-tyrrell', 'border-vanwall', 'border-venturi', 'border-veritas', 'border-virgin', 'border-watson', 'border-wetteroth', 'border-wolf-williams', 'border-wolf', 'border-zakspeed',

    // user theme
    'main-color', 'bg-light', 'bg-b-light', 'bg-s-light', 'text-t-s-light', 'text-light', 'border-light', 'bg-dark', 'bg-b-dark', 'bg-s-dark', 'bg-t-dark', 'text-t-s-dark', 'text-dark', 'text-hasnt-finished-race', 'border-dark'
  ],
  theme: {
    extend: {
      fontFamily: {
        bold: ['F1Bold', 'sans-serif'],
        regular: ['F1Regular', 'sans-serif'],
        wide: ['F1Wide', 'sans-serif']
      },
      colors: {
        // user theme
        'main-color': '#058785',
        'b-light': 'white',
        's-light': '#E9E9E7',
        't-s-light': '#4b5563',
        'light': 'black',
        'b-dark': '#191919',
        's-dark': '#333333',
        't-dark': '#058785',
        't-s-dark': '#d1d5db',
        'dark': 'white',
        'deconnect': '#F6A60B',
        'gold': 'gold',
        'hasnt-finished-race': '#717171',

        // live
        'stewardstxt': '#011132',
        'stewardsbg': '#E1E8F2',

        // actual constructors
        'red-bull': '#3671C6',
        'williams': '#64C4FF',
        'racing-bulls': '#6692FF',
        'mclaren': '#FF8000',
        'alpine': '#0093CC',
        'ferrari': '#E80020',
        'mercedes': '#27F4D2',
        'aston-martin': '#229971',
        'haas': '#B6BABD',
        'kick-sauber': '#52E252',

        // retro constructors - base color of the site for constructors without logo
        'adams': '#058785',
        'afm': '#a5b5dd',
        'ags': '#556da8',
        'alfa-romeo': '#aa121a',
        'alfa-special': '#058785',
        'alphatauri': '#011321',
        'alta': '#ef0505',
        'amon': '#403fff',
        'andrea-moda': '#0000ff',
        'apollon': '#d09719',
        'arrows': '#279cb4',
        'arzani-volpini': '#99440f',
        'aston-butterworth': '#ffffff',
        'ats-wheels': '#f9b418',
        'ats': '#126df9',
        'balsa': '#058785',
        'bar': '#94a582',
        'behra-porsche': '#058785',
        'bellasi': '#3c6d58',
        'benetton': '#018d30',
        'bmw-sauber': '#51a6d0',
        'bmw': '#51a6d0',
        'boro': '#e72210',
        'brabham': '#166f18',
        'brawn': '#e6ff01',
        'brm': '#57549c',
        'bromme': '#af140b',
        'brp': '#89b587',
        'bugatti': '#bf0032',
        'caterham': '#02432d',
        'christensen': '#058785',
        'cisitalia': '#060071',
        'coloni': '#feee00',
        'connaught': '#780137',
        'connew': '#951c12',
        'cooper': '#bdbfb3',
        'dallara': '#f7dd00',
        'de-tomaso': '#71ceec',
        'deidt': '#058785',
        'del-roy': '#058785',
        'derrington-francis': '#058785',
        'dunn': '#058785',
        'eagle': '#47464b',
        'eifelland': '#000080',
        'elder': '#058785',
        'emeryson': '#282828',
        'emw': '#cebc99',
        'enb': '#dfc139',
        'ensign': '#3a6a31',
        'epperly': '#058785',
        'era': '#a3c8e3',
        'eurobrun': '#fd7d2b',
        'ewing': '#058785',
        'ferguson': '#ffffff',
        'first': '#058785',
        'fittipaldi': '#f26926',
        'fondmetal': '#f0a701',
        'footwork': '#ff0033',
        'force-india': '#e66e05',
        'forti': '#373971',
        'frank-williams-racing-cars': '#ffffff',
        'frazer-nash': '#da2418',
        'fry': '#058785',
        'gilby': '#6c836a',
        'gordini': '#378cc4',
        'greifzu': '#058785',
        'hall': '#058785',
        'heck': '#058785',
        'hesketh': '#f9fb69',
        'hill': '#d61a1a',
        'honda': '#ed1831',
        'hrt': '#ad9950',
        'hwm': '#3f47cb',
        'iso-marlboro': '#c7af0d',
        'jaguar': '#ff1205',
        'jbw': '#3d242f',
        'jordan': '#ffff01',
        'kauhsen': '#ffff22',
        'klenk': '#9d053b',
        'kojima': '#0000ff',
        'krakau': '#058785',
        'kurtis-kraft': '#f8fee7',
        'kuzma': '#058785',
        'lancia': '#203f5f',
        'langley': '#058785',
        'larrousse': '#f61a23',
        'lds': '#65b7e0',
        'lec': '#a63434',
        'lesovsky': '#058785',
        'leyton-house': '#12c7be',
        'life': '#c63030',
        'ligier': '#13254e',
        'lola': '#fed904',
        'lotus-f1': '#b09247',
        'lotus-racing': '#003f22',
        'lotus': '#103728',
        'lyncar': '#2e4087',
        'maki': '#ac1f1f',
        'manor': '#fe6a35',
        'march': '#f7f0e7',
        'marchese': '#058785',
        'martini': '#3784f7',
        'marussia': '#fb3522',
        'maserati': '#0c2e59',
        'matra': '#001dd0',
        'mcguire': '#058785',
        'merzario': '#be423c',
        'meskowski': '#058785',
        'midland': '#ff0000',
        'minardi': '#0e233a',
        'modena': '#120a2f',
        'moore': '#058785',
        'nacke': '#058785',
        'nichels': '#727272',
        'olson': '#058785',
        'onyx': '#d2d68f',
        'osca': '#1a0382',
        'osella': '#fffe24',
        'pacific': '#0e90c9',
        'pankratz': '#058785',
        'parnelli': '#ffffff',
        'pawl': '#058785',
        'penske': '#d31a1b',
        'phillips': '#058785',
        'politoys': '#00007a',
        'porsche': '#ad8f3c',
        'prost': '#26468b',
        'protos': '#ff162a',
        'racing-point': '#f368ba',
        'rae': '#058785',
        'ram': '#0a6249',
        'rb': '#6692FF',
        'rebaque': '#048147',
        'reif': '#058785',
        'renault': '#fcd424',
        'rial': '#075cb0',
        'sauber': '#d6201c',
        'scarab': '#cdc6ce',
        'schroeder': '#058785',
        'scirocco': '#2a395a',
        'shadow': '#29240d',
        'shannon': '#283034',
        'sherman': '#058785',
        'simca-gordini': '#0177c8',
        'simtek': '#445eb9',
        'snowberger': '#058785',
        'spirit': '#2d4eb3',
        'spyker': '#ffffff',
        'stebro': '#feff00',
        'stevens': '#058785',
        'stewart': '#00002f',
        'super-aguri': '#ff0100',
        'surtees': '#fcf9fc',
        'sutton': '#058785',
        'talbot-lago': '#0047c1',
        'tec-mec': '#848474',
        'tecno': '#fee600',
        'theodore': '#4bfffe',
        'token': '#256e0a',
        'toleman': '#00236b',
        'toro-rosso': '#0120b9',
        'toyota': '#d6404c',
        'trevis': '#058785',
        'trojan': '#ee6463',
        'turner': '#e4ce22',
        'tyrrell': '#4665a1',
        'vanwall': '#74845a',
        'venturi': '#bc1313',
        'veritas': '#7badf9',
        'virgin': '#e31e23',
        'watson': '#058785',
        'wetteroth': '#058785',
        'wolf-williams': '#00279c',
        'wolf': '#ab240b',
        'zakspeed': '#c71701'
      },
    },
    plugins: [],
  }
}